### ISSUE TITLE
Being able to run a Gist

### ISSUE THREAD

**Issue by ashokgelal** [jrusbatch/compilify#23]
Probably via Chrome/ Firefox/ Safari extension or just with a javascript bookmarket. An example of this implementation: http://bl.ocks.org/

This would allow users to run many of the already written C# gists.

**Comment by jrusbatch** [comment]
This is a cool idea.

**Comment by khalidabuhakmeh** [comment]
A better solution might just be putting a url in. Maybe the code in question is in a github repository and you just need to pass in the raw url.
1. Click Load Button
2. A Modal pops up asking for a valid url
3. Click load, go retrieve the text at the url provided and run it through Roslyn.
4. If it compiles on the fly, load it into the editor, otherwise leave the editor as is.
