### ISSUE TITLE
How to reference System.Xml?

### ISSUE THREAD

**Issue by gilly3** [jrusbatch/compilify#69]
I can't seem to reference `System.Xml` or `System.Xml.Linq` at [compilify.net](https://compilify.net/).  I get:

> The type or namespace name 'Xml' does not exist in the namespace 'System' (are you missing an assembly reference?)

Am I doing something wrong?

**Comment by dpen2000** [comment]
I'm pretty sure this is because System.Xml is defined in System.Xml.Dll and the only assemblies referenced by Complify when compiling your code are listed here: https://github.com/Compilify/Compilify/blob/master/LanguageServices/LanguageServices/CSharpCompiler.cs#L39
See #28 for discussion of allowing custom assembly references.
